server:
  port: 9060
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lion?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: xiaoshuai123
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
